### ISSUE TITLE
[Bug] 구글 Places API 작동 오류

### ISSUE THREAD

**Issue by PIYUJIN** [Dont-forget6/Dont-Forget#15]
## 🚨 Description
할일 추가 및 상세 화면 위치 설정시 구글 Places API 작동하지 않는 오류 발생

## ✔️ 재현방법
1. 할일 추가 및 상세 화면에서
2. `위치 (위치 추가)`를 클릭하니
3. 구글 Places API 화면이
4. 글자를 입력하면 닫히는 오류가 발생했다.

## ❓ Expected behavior
프로젝트를 새로 만들면서 패키지명을 바꿔서 어플리케이션을 등록하고 발급받은 구글 API 키가 동작하지 않는 현상 발생

✅ local.properties의 google.map.key 값 변경하기  

## ETC
구글 API 키 값은 디스코드 '일반'에 올려두겠습니다.

혹시 디지털 지문(SHA1) 값을 입력해두지 않아서 구글 Places API가 동작하지 않을 수도 있습니다. 테스트 해보시고 동작하지 않는다면 저한테 디지털 지문(SHA1) 값을 보내주세요-!!

<br>

<div align="center">
<img width="545" alt="image" src="https://github.com/Dont-forget6/Dont-Forget/assets/86800087/760e4a4f-8f4b-4952-bf51-aa2d1ac0cb8d">
</div>

**Comment by PIYUJIN** [comment]
다들 확인하셨으면 comment 한번씩 달아주세요!

**Comment by ShShin98** [comment]
저도 같은 오류가 뜨네요
E6:48:F1:13:D9:1D:F2:A0:B7:5B:24:50:AA:C9:3B:BF:ED:F1:F4:5D 입니다!

**Comment by dlwngud** [comment]
저도 안되네요
C2:D1:91:49:E7:FD:0B:67:38:99:98:08:59:14:11:6C:EE:83:69:0B

**Comment by dkin12** [comment]
저도 전달하겠습니다
9D:A3:56:60:D1:1A:8D:01:C8:ED:BC:53:93:87:55:26:95:C3:1B:16

**Comment by PIYUJIN** [comment]
다 추가해뒀습니다! 


@JUNGCHAEYOON  채윤님도 올려주세요
